import Head from "next/head";
import { signOut, getSession, signIn } from "next-auth/react";
import Layout from "../components/layourmain";

export default function Home(session) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex h-screen bg-black">
          <div className="w-screen h-screen flex flex-col space-y-5 justify-center items-center">
            <button
              className="w-24 bg-gray-200 px-6 rounded-md"
              onClick={() => {
                signIn();
              }}
            >
              Iniciar session
            </button>
            <button
              className="w-24 bg-gray-200 px-6 rounded-md"
              onClick={() => {
                signOut();
              }}
            >
              Cerrar session
            </button>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });
  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: { ...session },
  };
}
